### ISSUE TITLE
Замечания @sylt-lingon лаб 1

### ISSUE THREAD

**Issue by ananasn** [sylt-lingon/laba1#1]
Замечаний особых нет, хорошая работа :+1: 

Единственное, думаю, что такую небольшую лабу можно было сделать в одном файле :)

**Comment by ananasn** [comment]
и еще одно замечание

```python
# Вместо 
for line in f.readlines():
    ...

# Лучше так
for line in f:
    ...
```

**Comment by sylt-lingon** [comment]
Добрый день! Исправила, спасибо.
